### PR TITLE
EXP-789 Campos com estado bloqueado estão com valores "transparentes" no Safari

### PR DESCRIPTION
**Pull request by LucasRichter**
## Context
Esse PR corrige a visualização de campo desabilitado que ocorre apenas no navegador Safari.

## Como testar

- Fazer o link dessa pacote buildado no projeto da Pilot
- Acessar a tela de "Dados cadastrais" no navegador Safari e os valores dos campos devem estar visiveis.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eea2faeae537e0489375c7cdc2ec63c146d172b7
  * Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eea2faeae537e0489375c7cdc2ec63c146d172b7
  * Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by diegodsgarcia — COMMENTED** [review]
Faltou apenas atualizar o `package,json` que o resto ta show!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eea2faeae537e0489375c7cdc2ec63c146d172b7
  * Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eea2faeae537e0489375c7cdc2ec63c146d172b7
  * Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by diegodsgarcia — APPROVED** [review]

**Review by rsmelo — APPROVED** [review]

**Pull request merged**
